name: PHP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  psalm:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Show psalm version
        run: vendor/bin/psalm --version

      - name: Run psalm validation
        run: vendor/bin/psalm --output-format=github --shepherd

  test:
    runs-on: ubuntu-latest
    needs:
      - build
      - psalm
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          coverage: xdebug

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run test suite
        run: php vendor/bin/phpunit

      - name: Check PhpUnit coverage percentage
        run: php vendor/bin/coverage-check build/logs/clover.xml 100

      - name: Upload coverage results to Coveralls
        run: php vendor/bin/php-coveralls --coverage_clover=build/logs/clover.xml -v
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
